#Creator: Sandrix33
#Twitch channel: https://www.twitch.tv/sandrix33
#Config version: 0.1
#Permission: 
#User: "CustomPlayerDrop.enabled"
#Admin: "CustomPlayerDrop.admin"

#[ITA]-Abilita CustomPlayerDrop
#[ENG]-Enable CustomPlayerDrop

CustomPlayerDrop: true 

#[ITA]-Messaggio di permesso mancante
#[ENG]-Missing permission message

permissionMessage: "&cYou are not allowed"


#[ITA]-Imposta CustomPlayerDrop solo quando un giocatore ne uccide un altro
#[ENG]-Set CustomPlayerDrop only when one player kills another

PlayerKillonly: false 

#[ITA]-Imposta se l'inventario del giocatore deve essere dato
#[ENG]-Set whether the player's inventory is to be given

DropPlayerInventory: true 

#[ITA]-Imposta se la testa del giocatore deve essere data
#[ENG]-Set whether the player's head is to be given

DropPlayerHead: false

#[ITA]-Imposta drop aggiuntivi
#[ENG]-Set additional drops
#[Format] - {Material Block}, {count}

ExtraDrop:
  - STONE, 20