#Creator: Sandrix33
#Permission: 
#User: "CustomPlayerDrop.enabled"
#Admin: "CustomPlayerDrop.admin"
#DO NOT CHANGE very important!
Version: 1.5
#true = plugin enabled
#false = plugin disabled
CustomPlayerDrop: true
permissionMessage: '&cYou are not allowed' 
#true = Plugin works at player kills
#false = Plugin works at any kills
PlayerKillonly: false
#{killer} placeholder for non-player kills
NonPlayerKiller: 'Something'
#true = Players drop their inventories
#false = Players don't drop their inventories
DropPlayerInventory: true
#true = Players drop their heads
#false = Players don't drop their heads
DropPlayerHead: true
HeadName: '&e{player}''s head'
HeadLore:
- ''
- '&b&lCustom Player Drop'
- ''
- '&fYou can drop enemies heads'
- '&fby killing them.'
- ''
- '&cKilled by &4&l{killer}'
#Chances to drop a player's head (in %)
HeadDropRate: 100
#true = plugin works only in a specific world
#false = plugin works everywhere
SpecificWorldOnly: false
Worlds:
- world
- world_nether
#true = drop a specific ammount of xp to killer
#false = drop player's xp (vanilla be like)
XpOnKill: false
#XP to give (not levels) - set to 0 no xp drop
XpGiveCount: 100
#true = give a specific ammount of money to killer (Essentials is needed)
#false = don't
MoneyOnKill: false
MoneyGiveCount: 100
#true = drop extra items on player's death 
#false = don't
EnableExtraDrop: true
#100 is used as name of the item and determines chance of drop (follow the same itemstack as example)
ExtraDrop:
  '100':
    ==: org.bukkit.inventory.ItemStack
    type: GHAST_TEAR
    amount: 1
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '&5&lSoul §dfragment'
      lore:
      - ''
      - '&b§lCustom Player Drop'
      - ''
      - '§fA piece of a §dplayer''s soul'
      - '§c§nbe careful! §fit may break.'
      - ''
      enchants:
        KNOCKBACK: 1
      Unbreakable: true
#true = to execute extra commands on player death 
#false = don't
EnableExtraCommands: false
ExtraCommands:
- effect give {killer} jump_boost 10 5
- tell {killer} &a&lYou have been rewarded with &b&nJump Boost V