#THIS IS AN EXAMPLE CONFIG IS USED TO REMEMBER COMMENTS 
#AND OTHER EXAMPLES THIS FILE IS UNUSED FROM PLUGIN
#IF YOU REMOVE IT, IT RECREATES AUTOMATICALLY

#Creator: Sandrix33
#Twitch channel: https://www.twitch.tv/sandrix33
#Permission: 
#User: "CustomPlayerDrop.enabled"
#Admin: "CustomPlayerDrop.admin"

#Important not remove or change!
Version: 1.4 

#[ITA]-Abilita CustomPlayerDrop
#[ENG]-Enable CustomPlayerDrop

CustomPlayerDrop: true 

#[ITA]-Messaggio di permesso mancante
#[ENG]-Missing permission message

permissionMessage: "&cYou are not allowed"

#[ITA]-Imposta CustomPlayerDrop solo quando un giocatore ne uccide un altro
#[ENG]-Set CustomPlayerDrop only when one player kills another

PlayerKillonly: false 

#[ITA]-Imposta se l'inventario del giocatore deve essere dato
#[ENG]-Set whether the player's inventory is to be given

DropPlayerInventory: true 

#[ITA]-Imposta se la testa del giocatore deve essere data
#[ENG]-Set whether the player's head is to be given

DropPlayerHead: true

#[ITA]-Imposta il nome e la descrizione della testa {player} = nome giocatore
#[ENG]-Set head name and lore {player} = Player's name

HeadName: "&6{player}'s head"
HeadLore: 
    - "&6{player}'s head lore"
    - "{player}'s head lore 2"
    - "&cKilled By {killer}"

#[ITA]-Imposta il rateo di drop della testa - è impostato in %
#[ENG]-Set the head drop rate - it is set in %

HeadDropRate: 100

#[ITA]-Specifica in quale mondo
#[ENG]-Specify in which world

SpecificWorldOnly: false

#[ITA]-Lista dei mondi
#[ENG]-Worlds list

Worlds:
    - "world"
    - "world_nether"

#[ITA]-Imposta il Drop di esperienza 
#[ENG]-Set the experience drop

XpOnKill: false

XpGiveCount: 100

#[ITA]-Imposta il guadagno di soldi - ATTENZIONE per questa feature si necessita di essentials e di PlayerKillonly su true!
#[ENG]-Set money earning - ATTENTION for this feature you need essentials and PlayerKillonly to true!

MoneyOnKill: false

MoneyGiveCount: 100

#[ITA]-Esegui comandi aggiuntivi alla morte del giocatore
#[ENG]-Set additional drops

EnableExtraCommands: false

ExtraCommands:
    - "eco take {player} 100"
    - "eco give {killer} 20"

#[ITA]-Imposta drop aggiuntivi
#[ENG]-Set additional drops

EnableExtraDrop: true		

#[ITA]-Nota! in questa sezione utilizza § al posto di & 
#[ENG]-Note! in this section use § instead of &

ExtraDrop:
  20: #Drop Rate as Name
    ==: org.bukkit.inventory.ItemStack
    type: STONE
    amount: 1
    meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §6Sample Item
        lore:
        - First line of lore
        - Second line of lore
        - §1Color §2support
        enchants:
          DAMAGE_ALL: 2
          KNOCKBACK: 7
          FIRE_ASPECT: 1