name: CustomPlayerDrop
main: CustomPlayerDrop.Sandrix.Dev.Main
author: Sandrix33
version: 1.2
description: Plugin for custom player drop
commands:
  CustomPlayerDrop:
    description: Commands for reload config 